server:
  port: 8089

spring:
  datasource:
    name: daruan
    url: jdbc:mysql://101.35.127.110:3306/daruan?useUnicode=true&characterEncoding=utf8
    username: root
    password: tzlTZL123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.daruan.entity


